Flowpack:
  ContentSecurityPolicy:
    enabled: true
    report-only: false
    throw-invalid-directive-exception: true
    content-security-policy:
      default:
        base-uri:
         'self': true
        connect-src:
          'self': true
        default-src:
          'self': true
        form-action:
          'self': true
        img-src:
          'self': true
        media-src:
          'self': true
        frame-src:
          'self': true
        object-src:
          'self': true
        script-src:
          'self': true
        style-src:
          'self': true
        style-src-attr:
          'self': true
        style-src-elem:
          'self': true
        font-src:
          'self': true
      custom: [ ]
      backend:
        base-uri:
          'self': true
        connect-src:
          'self': true
        default-src:
          'self': true
        form-action:
          'self': true
        img-src:
          'self': true
          'data:': true
        media-src:
          'self': true
        frame-src:
          'self': true
        object-src:
          'self': true
        script-src:
          'self': true
          'unsafe-inline': true
          'unsafe-eval': true
        style-src:
          'self': true
          'unsafe-inline': true
        style-src-attr:
          'self': true
          'unsafe-inline': true
        style-src-elem:
          'self': true
          'unsafe-inline': true
        font-src:
          'self': true
          'data:': true
      custom-backend: [ ]

Neos:
  Neos:
    fusion:
      autoInclude:
        Flowpack.ContentSecurityPolicy: true
  Flow:
    http:
      middlewares:
        'cspHeader':
          position: 'after routing'
          middleware: 'Flowpack\ContentSecurityPolicy\Http\CspHeaderMiddleware'
